cloud:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
